import { useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, DollarSign, Layers, Network, Pencil, Plus, RefreshCw, Save, ShoppingCart, Wifi } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import * as commerceApi from '../api/commerceApi';
import { DrawioDiagramViewer } from '../components/DrawioDiagramViewer';
import { useAuth } from '../context/AuthContext';
import type {
  NetworkBomLine,
  NetworkBomResult,
  NetworkDesignDetail,
  NetworkTopologyArtifact,
  OnboardingProfile,
} from '../types/commerce';

const CALCULATOR_RESULT_STORAGE_KEY = 'secureOfficeNetworkEstimateV1';
const CALCULATOR_INPUT_STORAGE_KEY = 'secureOfficeNetworkEstimateInputV1';
const BUSINESS_INTAKE_STORAGE_KEY = 'secureOfficeBusinessIntake';

const parseStorageJson = (key: string): Record<string, any> | null => {
  const raw = window.localStorage.getItem(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Record<string, any>;
  } catch {
    return null;
  }
};

const formatCurrency = (value: number): string =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value || 0);

const isQuoteRequiredLine = (line: NetworkBomLine): boolean => {
  const unit = Number(line.unit_price || 0);
  if (unit > 0) return false;
  const source = String(line.source_type || '').toLowerCase();
  return source === 'paapi' || source === 'derived';
};

const formatBomMoney = (line: NetworkBomLine, kind: 'unit' | 'total'): string => {
  const value = kind === 'unit' ? Number(line.unit_price || 0) : Number(line.line_total || 0);
  if (value <= 0 && isQuoteRequiredLine(line)) return 'Price on request';
  return formatCurrency(value);
};

const humanizeCategory = (value: string | null | undefined): string => {
  if (!value) return 'Other';
  return value.replace(/_/g, ' ').replace(/\b\w/g, (match) => match.toUpperCase());
};

const bomCategoryToCatalogCategory = (bomCategory: string | null | undefined): string => {
  const cat = String(bomCategory || '').toLowerCase();
  if (['phone'].includes(cat)) return 'phone';
  if (['tablet', 'laptop', 'desktop'].includes(cat)) return 'laptop';
  if (['cellular_backup', 'cellular_gateway'].includes(cat)) return 'hotspot';
  return 'router';
};

const vendorDisplayName = (vendor: string | null | undefined): string => {
  if (!vendor) return '-';
  const v = vendor.toLowerCase();
  if (v === 'papi' || v === 'paapi') return 'T-Mobile Device Catalog';
  return vendor;
};

const connectivityLabel = (value: NetworkBomLine['connectivity'] | undefined): string | null => {
  if (value === 'wired') return 'Wired link';
  if (value === 'wireless') return 'Wireless link';
  if (value === 'sim') return 'SIM / 5G link';
  return null;
};

const HIGHLIGHT_CATEGORIES = new Set([
  'wifi_ap',
  'switch',
  'firewall',
  'gateway',
  'security_appliance',
  'router',
  'cellular_backup',
  'cellular_gateway',
  'cabling',
  'camera',
  'sensor',
  'pos_systems',
  'digital_signage',
  'kiosks',
  'laptop',
  'desktop',
  'tablet',
  'phone',
]);

export const NetworkDesignBuilderPage = () => {
  const navigate = useNavigate();
  const { accessToken } = useAuth();
  const autoGeneratedRef = useRef(false);

  const [onboardingProfile, setOnboardingProfile] = useState<OnboardingProfile | null>(null);
  const [calculatorInput, setCalculatorInput] = useState<Record<string, any> | null>(null);
  const [calculatorResult, setCalculatorResult] = useState<Record<string, any> | null>(null);
  const [businessIntake, setBusinessIntake] = useState<Record<string, any> | null>(null);
  const [bom, setBom] = useState<NetworkBomResult | null>(null);
  const [topologyArtifact, setTopologyArtifact] = useState<NetworkTopologyArtifact | null>(null);
  const [savedDesign, setSavedDesign] = useState<NetworkDesignDetail | null>(null);
  const [designName, setDesignName] = useState('SMB Network Design');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [addingAllToCart, setAddingAllToCart] = useState(false);
  const [addingLineId, setAddingLineId] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');

  useEffect(() => {
    setCalculatorInput(parseStorageJson(CALCULATOR_INPUT_STORAGE_KEY));
    setCalculatorResult(parseStorageJson(CALCULATOR_RESULT_STORAGE_KEY));
    setBusinessIntake(parseStorageJson(BUSINESS_INTAKE_STORAGE_KEY));
  }, []);

  useEffect(() => {
    if (!accessToken) return;
    commerceApi.getOnboardingProfile(accessToken)
      .then((profile) => setOnboardingProfile(profile))
      .catch(() => setOnboardingProfile(null));
  }, [accessToken]);

  useEffect(() => {
    if (!onboardingProfile?.organization_name) return;
    setDesignName((prev) => (prev === 'SMB Network Design' ? `${onboardingProfile.organization_name} Network Design` : prev));
  }, [onboardingProfile]);

  useEffect(() => {
    if (!notice) return;
    const timer = window.setTimeout(() => setNotice(''), 2600);
    return () => window.clearTimeout(timer);
  }, [notice]);

  const ensureGeneratedArtifacts = async (): Promise<{ bomResult: NetworkBomResult; topologyResult: NetworkTopologyArtifact } | null> => {
    if (!accessToken || !calculatorResult) return null;
    setLoading(true);
    setError('');
    try {
      const bomResult = await commerceApi.generateNetworkBom(accessToken, {
        calculatorResult,
        businessContext: businessIntake || undefined,
      });
      const topologyResult = await commerceApi.generateNetworkTopology(accessToken, {
        bom: bomResult,
        businessContext: businessIntake || undefined,
      });
      setBom(bomResult);
      setTopologyArtifact(topologyResult);
      return { bomResult, topologyResult };
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to generate BOM/topology');
      return null;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!accessToken || !calculatorResult || bom || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void ensureGeneratedArtifacts();
  }, [accessToken, calculatorResult, bom]);

  const estimateCapex = useMemo(() => {
    const summaryCapex = Number(calculatorResult?.summary?.estimatedCapEx || 0);
    if (Number.isFinite(summaryCapex) && summaryCapex > 0) return summaryCapex;
    return Number(bom?.grand_total || 0);
  }, [calculatorResult, bom]);

  const recommendedApCount = useMemo(() => {
    const fromCalculator = Number(calculatorResult?.summary?.recommendedIndoorAPs || 0);
    if (Number.isFinite(fromCalculator) && fromCalculator > 0) return fromCalculator;
    return (bom?.line_items || []).filter((line) => line.category === 'wifi_ap').reduce((sum, line) => sum + line.quantity, 0);
  }, [calculatorResult, bom]);

  const recommendedSwitchCount = useMemo(() => {
    const fromCalculator = Number(calculatorResult?.summary?.recommendedSwitches || 0);
    if (Number.isFinite(fromCalculator) && fromCalculator > 0) return fromCalculator;
    return (bom?.line_items || []).filter((line) => line.category === 'switch').reduce((sum, line) => sum + line.quantity, 0);
  }, [calculatorResult, bom]);

  const bomHighlights = useMemo(() => {
    return (bom?.line_items || [])
      .filter((line) => HIGHLIGHT_CATEGORIES.has(String(line.category || '').toLowerCase()))
      .sort((a, b) => Number(b.line_total || 0) - Number(a.line_total || 0))
      .slice(0, 8);
  }, [bom]);

  const quoteRequiredCount = useMemo(
    () => (bom?.line_items || []).filter((line) => isQuoteRequiredLine(line)).length,
    [bom],
  );

  const eligibleCatalogLines = useMemo(() => {
    return (bom?.line_items || []).filter((line) => Boolean(line.item_id));
  }, [bom]);

  const onRegenerate = async () => {
    const artifacts = await ensureGeneratedArtifacts();
    if (artifacts) setNotice('Design regenerated.');
  };

  const onSaveDesign = async () => {
    if (!accessToken || !calculatorResult) return;
    const artifacts = bom && topologyArtifact
      ? { bomResult: bom, topologyResult: topologyArtifact }
      : await ensureGeneratedArtifacts();
    if (!artifacts) return;

    setSaving(true);
    setError('');
    try {
      const saved = await commerceApi.saveNetworkDesign(accessToken, {
        designId: savedDesign?.id,
        designName,
        calculatorInput: calculatorInput || {},
        calculatorResult,
        bom: artifacts.bomResult,
        topology: artifacts.topologyResult.topology || {},
        drawioXml: artifacts.topologyResult.drawioXml,
        assumptions: artifacts.topologyResult.summary.assumptions || artifacts.bomResult.assumptions || [],
        status: 'reviewed',
        submit: false,
      });
      setSavedDesign(saved);
      setNotice('Design saved to history.');
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to save design');
    } finally {
      setSaving(false);
    }
  };

  const onAddLineToCart = async (line: NetworkBomLine) => {
    if (!accessToken || !line.item_id) return;
    setAddingLineId(line.line_id);
    setError('');
    try {
      await commerceApi.addCartLine(accessToken, {
        catalog_item_id: line.item_id,
        quantity: Math.max(1, line.quantity),
      });
      setNotice(`Added ${line.name} to cart.`);
      setTimeout(() => navigate('/shop/cart'), 600);
    } catch (err: any) {
      setError(err?.response?.data?.detail || `Failed to add ${line.name} to cart`);
    } finally {
      setAddingLineId(null);
    }
  };

  const onAddAllToCart = async () => {
    if (!accessToken) return;
    if (eligibleCatalogLines.length === 0) {
      setNotice('No catalog-linked BOM items available to add.');
      return;
    }
    setAddingAllToCart(true);
    setError('');
    let successCount = 0;
    let failCount = 0;
    try {
      for (const line of eligibleCatalogLines) {
        try {
          await commerceApi.addCartLine(accessToken, {
            catalog_item_id: line.item_id as string,
            quantity: Math.max(1, line.quantity),
          });
          successCount += 1;
        } catch {
          failCount += 1;
        }
      }
      if (successCount > 0) {
        setNotice(`Added ${successCount} BOM item${successCount > 1 ? 's' : ''} to cart.`);
        setTimeout(() => navigate('/shop/cart'), 600);
      }
      if (failCount > 0) {
        setError(`${failCount} item${failCount > 1 ? 's' : ''} could not be added to cart.`);
      }
    } finally {
      setAddingAllToCart(false);
    }
  };

  return (
    <section className="content-wrap fade-in ndb-page">
      {/* Header */}
      <div className="ndb-header">
        <div className="ndb-header-left">
          <Link to="/shop/designs" className="ndb-back-link"><ArrowLeft size={16} /> Design History</Link>
          <h1>Network Design Builder</h1>
          <p className="lead">BOM and topology generated automatically from your intake and calculator data.</p>
        </div>
      </div>

      {!calculatorResult && (
        <article className="ndb-empty-state">
          <Layers size={36} strokeWidth={1.2} />
          <h3>Missing Intake Data</h3>
          <p>Complete business intake first so we can generate your network design.</p>
          <Link className="primary-btn" to="/business-intake">Open Business Intake</Link>
        </article>
      )}

      {error && <div className="onboarding-alert error">{error}</div>}
      {notice && <div className="toast-notice">{notice}</div>}

      {calculatorResult && (
        <div className="ndb-content">
          {/* Action Bar */}
          <div className="ndb-action-bar">
            <div className="ndb-design-name-wrap">
              <input
                className="ndb-design-name-input"
                value={designName}
                onChange={(e) => setDesignName(e.target.value)}
                placeholder="Design Name"
              />
              {savedDesign && <span className="mini-note">Saved</span>}
            </div>
            <div className="ndb-actions">
              <button className="ghost-btn ndb-action-btn" onClick={onRegenerate} disabled={loading}>
                <RefreshCw size={14} className={loading ? 'spin-icon' : ''} />
                {loading ? 'Generating...' : 'Regenerate'}
              </button>
              <button className="ghost-btn ndb-action-btn" onClick={onSaveDesign} disabled={saving || loading}>
                <Save size={14} />
                {saving ? 'Saving...' : 'Save'}
              </button>
              <button className="ghost-btn ndb-action-btn" onClick={() => navigate('/business-intake')}>
                <Pencil size={14} />
                Edit Requirements
              </button>
              <button className="ghost-btn ndb-action-btn" onClick={() => navigate('/shop/cart')}>
                <ShoppingCart size={14} />
                Cart
              </button>
              <button className="primary-btn ndb-action-btn" onClick={onAddAllToCart} disabled={addingAllToCart || eligibleCatalogLines.length === 0}>
                <Plus size={14} />
                {addingAllToCart ? 'Adding...' : `Add All to Cart (${eligibleCatalogLines.length})`}
              </button>
            </div>
          </div>

          {/* KPI Cards */}
          <div className="ndb-kpi-row">
            <div className="ndb-kpi-card ndb-kpi-capex">
              <div className="ndb-kpi-icon"><DollarSign size={18} /></div>
              <div className="ndb-kpi-info">
                <span className="ndb-kpi-label">Estimated CapEx</span>
                <strong className="ndb-kpi-value">{formatCurrency(estimateCapex)}</strong>
              </div>
            </div>
            <div className="ndb-kpi-card">
              <div className="ndb-kpi-icon"><Wifi size={18} /></div>
              <div className="ndb-kpi-info">
                <span className="ndb-kpi-label">Indoor APs</span>
                <strong className="ndb-kpi-value">{recommendedApCount}</strong>
              </div>
            </div>
            <div className="ndb-kpi-card">
              <div className="ndb-kpi-icon"><Network size={18} /></div>
              <div className="ndb-kpi-info">
                <span className="ndb-kpi-label">Switches</span>
                <strong className="ndb-kpi-value">{recommendedSwitchCount}</strong>
              </div>
            </div>
            <div className="ndb-kpi-card">
              <div className="ndb-kpi-icon"><Layers size={18} /></div>
              <div className="ndb-kpi-info">
                <span className="ndb-kpi-label">BOM Lines</span>
                <strong className="ndb-kpi-value">{bom?.line_items?.length || 0}</strong>
              </div>
            </div>
          </div>

          {/* Design Diagram - at top */}
          <article className="ndb-section">
            <div className="ndb-section-head">
              <h3>Network Topology</h3>
              <div className="ndb-topo-badges">
                <span className="ndb-topo-badge">{topologyArtifact?.summary?.nodeCount || 0} nodes</span>
                <span className="ndb-topo-badge">{topologyArtifact?.summary?.edgeCount || 0} edges</span>
              </div>
            </div>
            <p className="mini-note">
              Diagram lines show connectivity relationships, not exact physical cable routes.
              Labels are normalized as <strong>Wired link</strong>, <strong>Wireless link</strong>, and <strong>Managed connection</strong>.
            </p>
            {topologyArtifact?.drawioXml && (
              <DrawioDiagramViewer
                xml={topologyArtifact.drawioXml}
                title={`${designName || 'SMB Network Design'} Diagram Preview`}
                initialHeight={700}
              />
            )}
          </article>

          {/* Hardware Highlights */}
          <article className="ndb-section">
            <div className="ndb-section-head">
              <h3>Selected Hardware</h3>
              <span className="mini-note">{bomHighlights.length} top items by cost</span>
            </div>
            <div className="ndb-highlight-grid">
              {bomHighlights.map((line) => (
                <div key={line.line_id} className="ndb-highlight-card">
                  <div className="ndb-hc-top">
                    <span className="ndb-hc-category">{humanizeCategory(line.category)}</span>
                    <span className="ndb-hc-qty">{line.quantity}x</span>
                  </div>
                  <strong className="ndb-hc-name">{line.name}</strong>
                  <div className="ndb-hc-bottom">
                    <span className="ndb-hc-vendor">{vendorDisplayName(line.vendor)}</span>
                    <strong className="ndb-hc-price">{formatBomMoney(line, 'total')}</strong>
                  </div>
                </div>
              ))}
              {bomHighlights.length === 0 && (
                <div className="ndb-highlight-empty">
                  <p className="mini-note">Generating product selections...</p>
                </div>
              )}
            </div>
          </article>

          {/* BOM Table */}
          <article className="ndb-section">
            <div className="ndb-section-head">
              <h3>Bill of Materials</h3>
              <div className="ndb-bom-meta">
                {quoteRequiredCount > 0 && (
                  <span className="ndb-quote-badge">
                    {quoteRequiredCount} price-on-request
                  </span>
                )}
              </div>
            </div>
            {bom?.summary && <p className="mini-note" style={{ marginBottom: 10 }}>{bom.summary}</p>}
            {!!bom?.line_items?.length && (
              <div className="ndb-bom-table-wrap">
                <table className="ndb-bom-table">
                  <thead>
                    <tr>
                      <th className="ndb-th-item">Item</th>
                      <th>Category</th>
                      <th className="ndb-th-num">Qty</th>
                      <th className="ndb-th-num">Unit Price</th>
                      <th className="ndb-th-num">Total</th>
                      <th className="ndb-th-actions">Actions</th>
                    </tr>
                  </thead>
                  <tbody>
                    {bom.line_items.map((line, idx) => {
                      const canAdd = Boolean(line.item_id);
                      const isEven = idx % 2 === 0;
                      return (
                        <tr key={line.line_id} className={isEven ? 'ndb-row-even' : ''}>
                          <td className="ndb-td-item">
                            <strong>{line.name}</strong>
                            <span className="ndb-td-vendor">{vendorDisplayName(line.vendor)}</span>
                            {(line.connectivity || line.cable_type) && (
                              <span className="mini-note">
                                {line.cable_type && line.cable_length_meters
                                  ? `${line.cable_type} • ${Math.round(line.cable_length_meters)}m estimated • $${Number(line.price_per_meter || 0).toFixed(2)}/m`
                                  : connectivityLabel(line.connectivity)}
                              </span>
                            )}
                          </td>
                          <td><span className="ndb-cat-pill">{humanizeCategory(line.category)}</span></td>
                          <td className="ndb-td-num">{line.quantity}</td>
                          <td className="ndb-td-num">{formatBomMoney(line, 'unit')}</td>
                          <td className="ndb-td-num ndb-td-total">{formatBomMoney(line, 'total')}</td>
                          <td className="ndb-td-actions">
                            <button
                              className="ndb-edit-btn"
                              title="Edit in T-Mobile Device Catalog"
                              onClick={() => navigate(`/shop/routers?category=${bomCategoryToCatalogCategory(line.category)}`)}
                            >
                              <Pencil size={13} />
                            </button>
                            {canAdd ? (
                              <button
                                className="ndb-cart-btn"
                                onClick={() => onAddLineToCart(line)}
                                disabled={addingLineId === line.line_id}
                              >
                                <ShoppingCart size={13} />
                                {addingLineId === line.line_id ? 'Adding...' : 'Add to Cart'}
                              </button>
                            ) : (
                              <span className="ndb-no-catalog">Not catalog-linked</span>
                            )}
                          </td>
                        </tr>
                      );
                    })}
                  </tbody>
                </table>
              </div>
            )}
          </article>
        </div>
      )}
    </section>
  );
};
