import { useCallback, useEffect, useMemo, useRef, useState } from 'react';
import { ArrowLeft, DollarSign, Layers, Minus, Network, Pencil, Plus, RefreshCw, Save, ShoppingCart, Trash2, Wifi } from 'lucide-react';
import { Link, useNavigate } from 'react-router-dom';
import * as commerceApi from '../api/commerceApi';
import { DrawioDiagramViewer } from '../components/DrawioDiagramViewer';
import { useAuth } from '../context/AuthContext';
import { useShop } from '../context/ShopContext';
import type {
  ManagedServiceDeviceEntry,
  ManagedServicesDesignSummary,
  NetworkBomLine,
  NetworkBomResult,
  NetworkDesignDetail,
  NetworkTopologyArtifact,
  OnboardingProfile,
} from '../types/commerce';

const CALCULATOR_RESULT_STORAGE_KEY = 'secureOfficeNetworkEstimateV1';
const CALCULATOR_INPUT_STORAGE_KEY = 'secureOfficeNetworkEstimateInputV1';
const BUSINESS_INTAKE_STORAGE_KEY = 'secureOfficeBusinessIntake';

const parseStorageJson = (key: string): Record<string, any> | null => {
  const raw = window.localStorage.getItem(key);
  if (!raw) return null;
  try {
    return JSON.parse(raw) as Record<string, any>;
  } catch {
    return null;
  }
};

const formatCurrency = (value: number): string =>
  new Intl.NumberFormat('en-US', { style: 'currency', currency: 'USD', maximumFractionDigits: 2 }).format(value || 0);

const isQuoteRequiredLine = (line: NetworkBomLine): boolean => {
  const unit = Number(line.unit_price || 0);
  if (unit > 0) return false;
  const source = String(line.source_type || '').toLowerCase();
  return source === 'paapi' || source === 'derived';
};

const formatBomMoney = (line: NetworkBomLine, kind: 'unit' | 'total'): string => {
  const value = kind === 'unit' ? Number(line.unit_price || 0) : Number(line.line_total || 0);
  if (value <= 0 && isQuoteRequiredLine(line)) return 'Price on request';
  return formatCurrency(value);
};

const humanizeCategory = (value: string | null | undefined): string => {
  if (!value) return 'Other';
  return value.replace(/_/g, ' ').replace(/\b\w/g, (match) => match.toUpperCase());
};

const bomCategoryToCatalogCategory = (bomCategory: string | null | undefined): string => {
  const cat = String(bomCategory || '').toLowerCase();
  if (['phone'].includes(cat)) return 'phone';
  if (['tablet', 'laptop', 'desktop'].includes(cat)) return 'laptop';
  if (['cellular_backup', 'cellular_gateway'].includes(cat)) return 'hotspot';
  return 'router';
};

const vendorDisplayName = (vendor: string | null | undefined): string => {
  if (!vendor) return '-';
  const v = vendor.toLowerCase();
  if (v === 'papi' || v === 'paapi') return 'T-Mobile Device Catalog';
  return vendor;
};

const connectivityLabel = (value: NetworkBomLine['connectivity'] | undefined): string | null => {
  if (value === 'wired') return 'Wired link';
  if (value === 'wireless') return 'Wireless link';
  if (value === 'sim') return 'SIM / 5G link';
  return null;
};

const HIGHLIGHT_CATEGORIES = new Set([
  'wifi_ap',
  'switch',
  'firewall',
  'gateway',
  'security_appliance',
  'router',
  'cellular_backup',
  'cellular_gateway',
  'cabling',
  'camera',
  'sensor',
  'pos_systems',
  'digital_signage',
  'kiosks',
  'laptop',
  'desktop',
  'tablet',
  'phone',
]);

export const NetworkDesignBuilderPage = () => {
  const navigate = useNavigate();
  const { accessToken } = useAuth();
  const { cart, updateLineQuantity, removeLine } = useShop();
  const autoGeneratedRef = useRef(false);

  const [onboardingProfile, setOnboardingProfile] = useState<OnboardingProfile | null>(null);
  const [calculatorInput, setCalculatorInput] = useState<Record<string, any> | null>(null);
  const [calculatorResult, setCalculatorResult] = useState<Record<string, any> | null>(null);
  const [businessIntake, setBusinessIntake] = useState<Record<string, any> | null>(null);
  const [bom, setBom] = useState<NetworkBomResult | null>(null);
  const [topologyArtifact, setTopologyArtifact] = useState<NetworkTopologyArtifact | null>(null);
  const [savedDesign, setSavedDesign] = useState<NetworkDesignDetail | null>(null);
  const [designName, setDesignName] = useState('SMB Network Design');
  const [loading, setLoading] = useState(false);
  const [saving, setSaving] = useState(false);
  const [addingAllToCart, setAddingAllToCart] = useState(false);
  const [addingLineId, setAddingLineId] = useState<string | null>(null);
  const [error, setError] = useState('');
  const [notice, setNotice] = useState('');
  const [busyLineId, setBusyLineId] = useState<string | null>(null);
  const [msData, setMsData] = useState<ManagedServicesDesignSummary | null>(null);
  // Local MS price cache for pre-save state (fetched from catalog items)
  const [catalogMsPrices, setCatalogMsPrices] = useState<Map<string, number>>(new Map());
  // Local exclusion set for pre-save state
  const [localExcluded, setLocalExcluded] = useState<Set<string>>(new Set());

  const loadManagedServices = useCallback(async (designId: string) => {
    if (!accessToken) return;
    try {
      const data = await commerceApi.getDesignManagedServices(accessToken, designId);
      setMsData(data);
    } catch (err) {
      console.warn('[ManagedServices] Failed to load:', err);
    }
  }, [accessToken]);

  // Fetch MS prices from catalog for BOM item_ids (works before save)
  useEffect(() => {
    if (!accessToken || !bom?.line_items?.length) return;
    const itemIds = bom.line_items.map((l) => l.item_id).filter(Boolean) as string[];
    if (itemIds.length === 0) return;

    // Fetch all device catalog items to get managed_service_price
    commerceApi.getCatalog(accessToken, { type: 'DEVICE', page_size: 250 }).then((items) => {
      const priceMap = new Map<string, number>();
      for (const item of items) {
        if (item.managed_service_price != null && item.managed_service_price > 0) {
          priceMap.set(item.id, item.managed_service_price);
        }
      }
      setCatalogMsPrices(priceMap);
    }).catch(() => {});
  }, [accessToken, bom]);

  // Build per-item lookup — uses msData (after save) or catalogMsPrices (before save)
  const msDeviceMap = useMemo(() => {
    const map = new Map<string, ManagedServiceDeviceEntry & { group: string; groupEnabled: boolean }>();

    // If we have server MS data (after save), use it
    if (msData?.categories) {
      for (const cat of msData.categories) {
        for (const raw of (cat.devices || []) as any[]) {
          const device: ManagedServiceDeviceEntry = {
            itemId: raw.itemId || raw.item_id,
            name: raw.name,
            sku: raw.sku,
            category: raw.category,
            quantity: raw.quantity,
            managedServicePrice: raw.managedServicePrice ?? raw.managed_service_price ?? 0,
            excluded: raw.excluded ?? false,
          };
          if (device.itemId) {
            map.set(device.itemId, { ...device, group: cat.group, groupEnabled: cat.enabled !== false });
          }
        }
      }
      return map;
    }

    // Pre-save: build from BOM lines + catalogMsPrices
    if (bom?.line_items && catalogMsPrices.size > 0) {
      for (const line of bom.line_items) {
        if (!line.item_id) continue;
        const msPrice = catalogMsPrices.get(line.item_id);
        if (msPrice == null || msPrice <= 0) continue;
        map.set(line.item_id, {
          itemId: line.item_id,
          name: line.name,
          sku: line.sku || '',
          category: line.category || null,
          quantity: line.quantity,
          managedServicePrice: msPrice,
          excluded: localExcluded.has(line.item_id),
          group: '',
          groupEnabled: true,
        });
      }
    }
    return map;
  }, [msData, bom, catalogMsPrices, localExcluded]);

  const msTotalMonthly = useMemo(() => {
    if (msData?.grandTotalMonthly) return msData.grandTotalMonthly;
    // Pre-save: compute from local state
    let total = 0;
    for (const [, device] of msDeviceMap) {
      if (!device.excluded) {
        total += device.managedServicePrice * device.quantity;
      }
    }
    return total;
  }, [msData, msDeviceMap]);

  const toggleMsForDevice = async (itemId: string, currentlyExcluded: boolean) => {
    if (!accessToken) return;

    // Pre-save: toggle locally
    if (!savedDesign) {
      setLocalExcluded((prev) => {
        const next = new Set(prev);
        if (currentlyExcluded) next.delete(itemId);
        else next.add(itemId);
        return next;
      });
      return;
    }

    // Post-save: persist via API
    if (!msData) return;
    const config = msData.config || {};
    const enabledSet = new Set<string>((config as any).enabled_categories || (config as any).enabledCategories || []);
    const excludedSet = new Set<string>((config as any).excluded_item_ids || (config as any).excludedItemIds || []);

    const deviceInfo = msDeviceMap.get(itemId);
    if (deviceInfo && !enabledSet.has(deviceInfo.group)) {
      enabledSet.add(deviceInfo.group);
    }

    if (currentlyExcluded) {
      excludedSet.delete(itemId);
    } else {
      excludedSet.add(itemId);
    }

    // Optimistic update
    setMsData((prev) => {
      if (!prev) return prev;
      const newExcluded = !currentlyExcluded;
      return {
        ...prev,
        categories: prev.categories.map((cat) => ({
          ...cat,
          enabled: enabledSet.has(cat.group),
          devices: cat.devices.map((d: any) =>
            (d.itemId || d.item_id) === itemId ? { ...d, excluded: newExcluded } : d
          ),
          monthlyTotal: cat.devices.reduce((sum: number, d: any) => {
            const id = d.itemId || d.item_id;
            const exc = id === itemId ? newExcluded : d.excluded;
            const price = d.managedServicePrice ?? d.managed_service_price ?? 0;
            return sum + (exc ? 0 : price * d.quantity);
          }, 0),
        })),
      };
    });

    try {
      const result = await commerceApi.updateDesignManagedServices(accessToken, savedDesign.id, {
        enabledCategories: [...enabledSet],
        excludedItemIds: [...excludedSet],
      });
      setMsData(result);
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to update managed service');
      loadManagedServices(savedDesign.id);
    }
  };

  const cartLineByItemId = useMemo(() => {
    const map = new Map<string, { lineId: string; quantity: number }>();
    if (!cart?.lines) return map;
    for (const line of cart.lines) {
      map.set(line.catalog_item_id, { lineId: line.id, quantity: line.quantity });
    }
    return map;
  }, [cart]);

  const handleBomQtyChange = async (itemId: string, lineId: string, newQty: number) => {
    setBusyLineId(itemId);
    try {
      if (newQty <= 0) await removeLine(lineId);
      else await updateLineQuantity(lineId, newQty);
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to update quantity');
    } finally {
      setBusyLineId(null);
    }
  };

  useEffect(() => {
    setCalculatorInput(parseStorageJson(CALCULATOR_INPUT_STORAGE_KEY));
    setCalculatorResult(parseStorageJson(CALCULATOR_RESULT_STORAGE_KEY));
    setBusinessIntake(parseStorageJson(BUSINESS_INTAKE_STORAGE_KEY));
  }, []);

  useEffect(() => {
    if (!accessToken) return;
    commerceApi.getOnboardingProfile(accessToken)
      .then((profile) => setOnboardingProfile(profile))
      .catch(() => setOnboardingProfile(null));
  }, [accessToken]);

  useEffect(() => {
    if (!onboardingProfile?.organization_name) return;
    setDesignName((prev) => (prev === 'SMB Network Design' ? `${onboardingProfile.organization_name} Network Design` : prev));
  }, [onboardingProfile]);

  useEffect(() => {
    if (!notice) return;
    const timer = window.setTimeout(() => setNotice(''), 2600);
    return () => window.clearTimeout(timer);
  }, [notice]);

  const ensureGeneratedArtifacts = async (): Promise<{ bomResult: NetworkBomResult; topologyResult: NetworkTopologyArtifact } | null> => {
    if (!accessToken || !calculatorResult) return null;
    setLoading(true);
    setError('');
    try {
      const bomResult = await commerceApi.generateNetworkBom(accessToken, {
        calculatorResult,
        businessContext: businessIntake || undefined,
      });
      const topologyResult = await commerceApi.generateNetworkTopology(accessToken, {
        bom: bomResult,
        businessContext: businessIntake || undefined,
      });
      setBom(bomResult);
      setTopologyArtifact(topologyResult);
      return { bomResult, topologyResult };
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to generate BOM/topology');
      return null;
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    if (!accessToken || !calculatorResult || bom || autoGeneratedRef.current) return;
    autoGeneratedRef.current = true;
    void ensureGeneratedArtifacts();
  }, [accessToken, calculatorResult, bom]);

  const estimateCapex = useMemo(() => {
    const summaryCapex = Number(calculatorResult?.summary?.estimatedCapEx || 0);
    if (Number.isFinite(summaryCapex) && summaryCapex > 0) return summaryCapex;
    return Number(bom?.grand_total || 0);
  }, [calculatorResult, bom]);

  const recommendedApCount = useMemo(() => {
    const fromCalculator = Number(calculatorResult?.summary?.recommendedIndoorAPs || 0);
    if (Number.isFinite(fromCalculator) && fromCalculator > 0) return fromCalculator;
    return (bom?.line_items || []).filter((line) => line.category === 'wifi_ap').reduce((sum, line) => sum + line.quantity, 0);
  }, [calculatorResult, bom]);

  const recommendedSwitchCount = useMemo(() => {
    const fromCalculator = Number(calculatorResult?.summary?.recommendedSwitches || 0);
    if (Number.isFinite(fromCalculator) && fromCalculator > 0) return fromCalculator;
    return (bom?.line_items || []).filter((line) => line.category === 'switch').reduce((sum, line) => sum + line.quantity, 0);
  }, [calculatorResult, bom]);

  const bomHighlights = useMemo(() => {
    return (bom?.line_items || [])
      .filter((line) => HIGHLIGHT_CATEGORIES.has(String(line.category || '').toLowerCase()))
      .sort((a, b) => Number(b.line_total || 0) - Number(a.line_total || 0))
      .slice(0, 8);
  }, [bom]);

  const quoteRequiredCount = useMemo(
    () => (bom?.line_items || []).filter((line) => isQuoteRequiredLine(line)).length,
    [bom],
  );

  const eligibleCatalogLines = useMemo(() => {
    return (bom?.line_items || []).filter((line) => Boolean(line.item_id));
  }, [bom]);

  const onRegenerate = async () => {
    const artifacts = await ensureGeneratedArtifacts();
    if (artifacts) setNotice('Design regenerated.');
  };

  const onSaveDesign = async () => {
    if (!accessToken || !calculatorResult) return;
    const artifacts = bom && topologyArtifact
      ? { bomResult: bom, topologyResult: topologyArtifact }
      : await ensureGeneratedArtifacts();
    if (!artifacts) return;

    setSaving(true);
    setError('');
    try {
      const saved = await commerceApi.saveNetworkDesign(accessToken, {
        designId: savedDesign?.id,
        designName,
        calculatorInput: calculatorInput || {},
        calculatorResult,
        bom: artifacts.bomResult,
        topology: artifacts.topologyResult.topology || {},
        drawioXml: artifacts.topologyResult.drawioXml,
        assumptions: artifacts.topologyResult.summary.assumptions || artifacts.bomResult.assumptions || [],
        status: 'reviewed',
        submit: false,
      });
      setSavedDesign(saved);
      loadManagedServices(saved.id);
      setNotice('Design saved to history.');
    } catch (err: any) {
      setError(err?.response?.data?.detail || 'Failed to save design');
    } finally {
      setSaving(false);
    }
  };

  const onAddLineToCart = async (line: NetworkBomLine) => {
    if (!accessToken || !line.item_id) return;
    setAddingLineId(line.line_id);
    setError('');
    try {
      await commerceApi.addCartLine(accessToken, {
        catalog_item_id: line.item_id,
        quantity: Math.max(1, line.quantity),
      });
      setNotice(`Added ${line.name} to cart.`);
      setTimeout(() => navigate('/shop/cart'), 600);
    } catch (err: any) {
      setError(err?.response?.data?.detail || `Failed to add ${line.name} to cart`);
    } finally {
      setAddingLineId(null);
    }
  };

  const onAddAllToCart = async () => {
    if (!accessToken) return;
    if (eligibleCatalogLines.length === 0) {
      setNotice('No catalog-linked BOM items available to add.');
      return;
    }
    setAddingAllToCart(true);
    setError('');
    let successCount = 0;
    let failCount = 0;
    try {
      for (const line of eligibleCatalogLines) {
        try {
          await commerceApi.addCartLine(accessToken, {
            catalog_item_id: line.item_id as string,
            quantity: Math.max(1, line.quantity),
          });
          successCount += 1;
        } catch {
          failCount += 1;
        }
      }
      if (successCount > 0) {
        setNotice(`Added ${successCount} BOM item${successCount > 1 ? 's' : ''} to cart.`);
        setTimeout(() => navigate('/shop/cart'), 600);
      }
      if (failCount > 0) {
        setError(`${failCount} item${failCount > 1 ? 's' : ''} could not be added to cart.`);
      }
    } finally {
      setAddingAllToCart(false);
    }
  };

  return (
    <section className="content-wrap fade-in">
      <div className="content-head row-between">
        <div>
          <h1>Network Design Builder</h1>
          <p className="lead">BOM and topology generated automatically from your intake and calculator data.</p>
        </div>
        <Link to="/shop/designs" className="ghost-link">Back to Design History</Link>
      </div>

      {!calculatorResult && (
        <article className="ndb-empty-state">
          <Layers size={36} strokeWidth={1.2} />
          <h3>Missing Intake Data</h3>
          <p>Complete business intake first so we can generate your network design.</p>
          <Link className="primary-btn" to="/business-intake">Open Business Intake</Link>
        </article>
      )}

      {error && <div className="onboarding-alert error">{error}</div>}
      {notice && <div className="toast-notice">{notice}</div>}

      {calculatorResult && (
        <section className="dashboard-grid">
          {/* Request Summary */}
          <article className="dashboard-panel">
            <h3>Request Summary</h3>
            <div className="ndb-design-name-wrap" style={{ marginBottom: 10 }}>
              <input
                className="ndb-design-name-input"
                value={designName}
                onChange={(e) => setDesignName(e.target.value)}
                placeholder="Design Name"
              />
              {savedDesign && <span className="mini-note">Saved</span>}
            </div>
            <p className="mini-note">Status: <span className="badge">{savedDesign ? 'Reviewed' : 'Draft'}</span></p>
            <div className="dashboard-kpi-grid">
              <div>
                <span>Estimated CapEx</span>
                <strong>{formatCurrency(estimateCapex)}</strong>
              </div>
              <div>
                <span>AP Count</span>
                <strong>{recommendedApCount}</strong>
              </div>
              <div>
                <span>Switch Count</span>
                <strong>{recommendedSwitchCount}</strong>
              </div>
            </div>
            <div className="dashboard-link-row">
              <button className="ghost-btn" onClick={onRegenerate} disabled={loading}>
                <RefreshCw size={14} className={loading ? 'spin-icon' : ''} />
                {loading ? 'Generating...' : 'Regenerate'}
              </button>
              <button className="ghost-btn" onClick={onSaveDesign} disabled={saving || loading}>
                <Save size={14} />
                {saving ? 'Saving...' : 'Save'}
              </button>
              <button className="ghost-btn" onClick={() => navigate('/business-intake')}>
                <Pencil size={14} /> Edit Requirements
              </button>
              <button className="ghost-btn" onClick={() => navigate('/shop/cart')}>
                <ShoppingCart size={14} /> Cart
              </button>
            </div>
          </article>

          {/* BOM Lines KPI */}
          <article className="dashboard-panel">
            <h3>Design Overview</h3>
            <p className="mini-note">BOM Lines: <strong>{bom?.line_items?.length || 0}</strong></p>
            <p className="mini-note">Catalog-linked items: <strong>{eligibleCatalogLines.length}</strong></p>
            {quoteRequiredCount > 0 && (
              <p className="mini-note">{quoteRequiredCount} price-on-request pending final quote.</p>
            )}
            <div className="dashboard-link-row" style={{ marginTop: 12 }}>
              <button className="primary-btn" onClick={onAddAllToCart} disabled={addingAllToCart || eligibleCatalogLines.length === 0}>
                <Plus size={14} />
                {addingAllToCart ? 'Adding...' : `Add All to Cart (${eligibleCatalogLines.length})`}
              </button>
            </div>
          </article>

          {/* Diagram / Topology Reference */}
          <article className="dashboard-panel full-width" id="design-diagram">
            <h3>Diagram / Topology Reference</h3>
            <p className="mini-note">
              Topology lines represent connectivity relationships rather than literal cable routing paths:
              Wired link, Wireless link, and Managed connection.
            </p>
            <div className="integration-grid">
              <div className="integration-card">
                <div className="row-between">
                  <strong>Topology Nodes</strong>
                  <span className="badge">{topologyArtifact?.summary?.nodeCount || 0}</span>
                </div>
              </div>
              <div className="integration-card">
                <div className="row-between">
                  <strong>Topology Edges</strong>
                  <span className="badge">{topologyArtifact?.summary?.edgeCount || 0}</span>
                </div>
              </div>
            </div>
            {topologyArtifact?.drawioXml && (
              <DrawioDiagramViewer
                xml={topologyArtifact.drawioXml}
                title={`${designName || 'SMB Network Design'} Diagram Preview`}
                initialHeight={700}
              />
            )}
          </article>

          {/* Equipment / BOM Table */}
          <article className="dashboard-panel full-width" id="design-bom">
            <h3>Equipment / BOM Snapshot</h3>
            {bom?.summary && <p className="mini-note" style={{ marginBottom: 10 }}>{bom.summary}</p>}
            {!!bom?.line_items?.length && (
              <table className="cart-table">
                <thead>
                  <tr>
                    <th>Name</th>
                    <th>Category</th>
                    <th>Qty</th>
                    <th>Unit Price</th>
                    <th>Total</th>
                    <th>Managed Service</th>
                    <th></th>
                  </tr>
                </thead>
                <tbody>
                  {bom.line_items.map((line) => {
                    const canAdd = Boolean(line.item_id);
                    const msDevice = line.item_id ? msDeviceMap.get(line.item_id) : undefined;
                    const hasMsPrice = msDevice && msDevice.managedServicePrice > 0;
                    const msIncluded = hasMsPrice && msDevice.groupEnabled && !msDevice.excluded;
                    return (
                      <tr key={line.line_id}>
                        <td>
                          <div>{line.name}</div>
                          <div className="mini-note">{vendorDisplayName(line.vendor)}</div>
                          {(line.connectivity || line.cable_type) && (
                            <div className="mini-note">
                              {line.cable_type && line.cable_length_meters
                                ? `${line.cable_type} • ${Math.round(line.cable_length_meters)}m estimated • $${Number(line.price_per_meter || 0).toFixed(2)}/m`
                                : connectivityLabel(line.connectivity)}
                            </div>
                          )}
                        </td>
                        <td>{humanizeCategory(line.category)}</td>
                        <td>{line.quantity}</td>
                        <td>{formatBomMoney(line, 'unit')}</td>
                        <td>{formatBomMoney(line, 'total')}</td>
                        <td>
                          {hasMsPrice ? (
                            <label className="ms-inline-check">
                              <input
                                type="checkbox"
                                checked={msIncluded}
                                disabled={false}
                                onChange={() => toggleMsForDevice(msDevice.itemId, !msDevice.excluded ? false : true)}
                              />
                              <span className={msIncluded ? 'ms-inline-price' : 'ms-inline-price ms-inline-excluded'}>
                                ${msDevice.managedServicePrice.toFixed(2)}/mo
                              </span>
                            </label>
                          ) : (
                            <span className="mini-note">—</span>
                          )}
                        </td>
                        <td>
                          {canAdd ? (() => {
                            const cl = cartLineByItemId.get(line.item_id as string);
                            if (cl) {
                              return (
                                <div className="qty-stepper">
                                  <button className="qty-stepper-btn" disabled={busyLineId === line.item_id}
                                    onClick={() => cl.quantity <= 1
                                      ? handleBomQtyChange(line.item_id as string, cl.lineId, 0)
                                      : handleBomQtyChange(line.item_id as string, cl.lineId, cl.quantity - 1)
                                    }
                                  >
                                    {cl.quantity <= 1 ? <Trash2 size={13} /> : <Minus size={13} />}
                                  </button>
                                  <span className="qty-stepper-value">{cl.quantity}</span>
                                  <button className="qty-stepper-btn" disabled={busyLineId === line.item_id}
                                    onClick={() => handleBomQtyChange(line.item_id as string, cl.lineId, cl.quantity + 1)}
                                  >
                                    <Plus size={13} />
                                  </button>
                                </div>
                              );
                            }
                            return (
                              <button
                                className="secondary-btn"
                                style={{ fontSize: '0.78rem', padding: '5px 10px', display: 'flex', alignItems: 'center', gap: 4 }}
                                onClick={() => onAddLineToCart(line)}
                                disabled={addingLineId === line.line_id}
                              >
                                <ShoppingCart size={13} />
                                {addingLineId === line.line_id ? 'Adding...' : 'Add to Cart'}
                              </button>
                            );
                          })() : (
                            <span className="mini-note">—</span>
                          )}
                        </td>
                      </tr>
                    );
                  })}
                </tbody>
                {msTotalMonthly > 0 && (
                  <tfoot>
                    <tr className="ms-total-row">
                      <td colSpan={5} style={{ textAlign: 'right', fontWeight: 600 }}>
                        Total Managed Services
                      </td>
                      <td className="ms-inline-total">
                        {formatCurrency(msTotalMonthly)}/mo
                      </td>
                      <td></td>
                    </tr>
                  </tfoot>
                )}
              </table>
            )}
            {(!bom?.line_items?.length) && (
              <p className="mini-note">No BOM lines found. Click "Regenerate" to generate.</p>
            )}
          </article>
        </section>
      )}
    </section>
  );
};
